{"content": {"suites": {"0": {"status": {"total_pass": 0, "total_skip": 0, "total_xpass": 0, "total_xfail": 0, "total_rerun": 0, "total_fail": 1, "total_error": 0}, "tests": {"0": {"status": "FAIL", "message": "       ssl.SSLCertVerificationError: [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: self signed certificate (_ssl.c:1123)\n       urllib3.exceptions.MaxRetryError: HTTPSConnectionPool(host='thetestingworldapi.com', port=443): Max retries exceeded with url: /Token (Caused by SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: self signed certificate (_ssl.c:1123)')))\n           requests.exceptions.SSLError: HTTPSConnectionPool(host='thetestingworldapi.com', port=443): Max retries exceeded with url: /Token (Caused by SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: self signed certificate (_ssl.c:1123)')))\n", "test_name": "test_oauth_api", "rerun": "0"}}, "suite_name": "test_oAuthentication.py"}}}, "date": "June 27, 2022", "start_time": 1656316205.1062186, "total_suite": 1, "status": "FAIL", "status_list": {"pass": "0", "fail": "1", "skip": "0", "error": "0", "xpass": "0", "xfail": "0", "rerun": "0"}, "total_tests": "1"}